### ISSUE TITLE
Generating a new Desktop/Web font file from PNGs?

### ISSUE THREAD

**Issue by myselfhimself** [robhagemans/monobit#1]
Hello,
Thank you for this project which seems very clean and very well organized!!!
I would like to be sure that your project could help mine, which generates new letter renders for now.

I am generating black and white letters (could be any color on transparent background, or vector graphics as well), as shown here: https://github.com/labonneimpression/pix2chocolate#example-3---multiple-letter-chocolate-biscuits
using mostly python scripts and various executables.
For now my output file format is .png with background, but I can for sure end up other raster or vector formats if needed, without problem.
I would like to output some day a font that I could use in LibreOffice or Inkscape, or maybe any web page, loadable by CSS font-face, out of my generate letters image.

Could you please advise a way to use your tool to convert my raster or vector letter images into a proper font file for desktop/web applications?

Thanks!!

**Comment by robhagemans** [comment]
Hi, `monobit` is aimed at bitmap fonts only - if you want to use fonts on the web or in Inkscape, you'll need scalable vector fonts (e.g. `.ttf` or `.woff` formats) which this project can't help you with... In any case since you can produce vector outputs you would lose a lot of quality by going to bitmap first and then converting back. 

Perhaps check out https://fontforge.org - I'm not super familiar with it but I think it can import `.svg` vector files and produce a number of vector font formats. It's also scriptable through Python though the documentation on this is a bit limited (see here: https://fontforge.org/docs/scripting/python.html). Good luck!

**Comment by myselfhimself** [comment]
Hello !! Thanks for the very nice answer..
I will go for automated path tracing and am now digging into
https://github.com/nfroidure/gulp-iconfont/issues and fontforge then!!
I will give you feedback!!
Have a nice day!!

so 31. 10. 2020 v 9:26 odesílatel Rob Hagemans <notifications@github.com>
napsal:
